name: open_weather_api
description: A new Flutter project.
version: 0.1.0

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  http: ^0.13.0
  json_annotation: ^4.4.0

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  mocktail: ^0.2.0
  test: ^1.16.4
  coverage: ^1.0.3

